# Generated by Django 4.2 on 2023-12-23 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=256, verbose_name='Brand Name *')),
                ('cuisine_type', models.CharField(blank=True, choices=[('Asian food', 'Asian food'), ('European cuisine', 'European cuisine'), ('Cuisine of the Americas', 'Cuisine of the Americas'), ('African cuisine', 'African cuisine')], max_length=128, null=True)),
                ('address', models.CharField(max_length=256, verbose_name='Address *')),
            ],
        ),
    ]
