FROM dj_base

WORKDIR /app

ENV VIRTUAL_ENV=/opt/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

COPY . .
RUN python -m pip install --upgrade pip && \
    pip3 install -r requirements.txt 
